---
title       : Cognitive control of eye movements
subtitle    : A model of voluntary and involuntary saccade generation
author      : Ryan M. Hope
job         : CogWorks Lab, Rensselaer Polytechnic Institute
biglogo     : rpi_logo.png
logo        : cogworks_logo.png
framework   : io2012
highlighter : highlight.js
hitheme     : tomorrow
widgets     : [mathjax]
mode        : selfcontained
knit        : slidify::knit2slides
github      : 
              author  : ryanhope
              repo    : issues_fall2015
    
---

## Voluntary vs involuntary control

Everything that involves mo

---

## Goals

High level

+ Gain better understanding of cognitive control
    - Proactive vs Reactive
    - Voluntary vs Involuntary
    - Automatic vs Deliberate

Low level

+ Develop a model of oculomotor control
    - Understand how temporary voluntary control of automatic processes takes place

---

## Why model eye movements?

+ Humans make around 2-4 eye movements every second
    - Thats about 80,000 to 160,000 eye movements a day, more than any other motor based activity
+ Although it appears that humans can initiate a saccade to a target at will, most saccades are automatic or involuntary
+ Eye movements only have 2 degrees of freedom (left/right, up/down)
    - Probably the simplest motor activity to model

---

## What are involuntary eye movements?

+ Eye movements 

---

## The role of attention in eye movements

+ There is lots of evidence to suggest that covert shifts of attention always preceede voluntary eye movements
+ It is less clear whether or not this is also true for involuntary eye movements
    - Some think the sudden onset of visual stimuli captures attention 100% of the time
    - More recent evidence suggests a less strict coupling